data_dir:
  crema_d: /project/shrikann_35/tiantiaf/ser-data/CREMA-D/
  iemocap: /project/shrikann_35/tiantiaf/ser-data/iemocap/
  meld: /project/shrikann_35/tiantiaf/ser-data/MELD.Raw/
  msp-improv: /project/shrikann_35/tiantiaf/ser-data/MSP-IMPROV/
  msp-podcast: /project/shrikann_35/tiantiaf/ser-data/MSP-podcast
  ravdess: /project/shrikann_35/tiantiaf/ser-data/Ravdess
  commsense: /data/dataset/transformer_sentence/data
project_dir: /output
